-- PostgreSQL: área intermediária isolada. Não altera tabelas publicadas do projeto.
-- Executar uma vez no banco de desenvolvimento; nomes sem aspas seguem lowercase.

CREATE SCHEMA IF NOT EXISTS stg_tse;

-- Escopo atual do load: AC, AL, BA, DF, RO e SP. Para outro recorte, altere
-- esta lista e a constante UFS do normalizador Python para manter as cargas iguais.
CREATE TABLE IF NOT EXISTS stg_tse.escopo_uf (
    sg_uf char(2) PRIMARY KEY CHECK (sg_uf = upper(sg_uf))
);
DELETE FROM stg_tse.escopo_uf
WHERE sg_uf NOT IN ('AC', 'AL', 'BA', 'DF', 'RO', 'SP');
INSERT INTO stg_tse.escopo_uf (sg_uf)
VALUES ('AC'), ('AL'), ('BA'), ('DF'), ('RO'), ('SP')
ON CONFLICT DO NOTHING;

-- Espelho tipado só no nível de lote. Campos de origem continuam TEXT para não
-- converter #NULO/-1, #NE/-3 e -4/NÃO DIVULGÁVEL em zero nem perder códigos.
CREATE TABLE IF NOT EXISTS stg_tse.candidatura (
    ano_eleicao text NOT NULL,
    cd_eleicao text,
    nr_turno text,
    cd_tipo_eleicao text,
    nm_tipo_eleicao text,
    sg_uf text,
    sg_ue text,
    nm_ue text,
    cd_cargo text,
    ds_cargo text,
    sq_candidato text NOT NULL,
    nr_cpf_candidato text,
    nm_candidato text,
    nm_urna_candidato text,
    dt_nascimento text,
    ds_grau_instrucao text,
    ds_genero text,
    ds_cor_raca text,
    nr_partido text,
    sg_partido text,
    nm_partido text,
    ds_sit_tot_turno text,
    source_file text NOT NULL,
    nr_titulo_eleitoral_candidato text
);

ALTER TABLE stg_tse.candidatura
    ADD COLUMN IF NOT EXISTS nm_urna_candidato text;

CREATE TABLE IF NOT EXISTS stg_tse.votacao_candidato_munzona (
    ano_eleicao text NOT NULL,
    sg_uf text NOT NULL,
    cd_eleicao text NOT NULL,
    nr_turno text NOT NULL,
    cd_cargo text NOT NULL,
    cd_municipio_tse text NOT NULL,
    sq_candidato text NOT NULL,
    qt_votos_nominais text,
    source_file text NOT NULL
);

CREATE TABLE IF NOT EXISTS stg_tse.votacao_partido_munzona (
    ano_eleicao text NOT NULL,
    sg_uf text NOT NULL,
    cd_eleicao text NOT NULL,
    nr_turno text NOT NULL,
    cd_cargo text NOT NULL,
    cd_municipio_tse text NOT NULL,
    nr_partido text NOT NULL,
    sg_partido text,
    qt_votos_legenda text,
    qt_votos_nominais text,
    source_file text NOT NULL
);

CREATE TABLE IF NOT EXISTS stg_tse.detalhe_votacao_munzona (
    ano_eleicao text NOT NULL,
    sg_uf text NOT NULL,
    cd_eleicao text NOT NULL,
    nr_turno text NOT NULL,
    cd_cargo text,
    cd_municipio_tse text NOT NULL,
    nr_zona text NOT NULL,
    qt_aptos text,
    qt_comparecimento text,
    qt_abstencao text,
    source_file text NOT NULL
);

CREATE TABLE IF NOT EXISTS stg_tse.perfil_eleitorado_municipio (
    ano_eleicao text NOT NULL,
    sg_uf text NOT NULL,
    cd_municipio_tse text NOT NULL,
    nr_zona text,
    ds_faixa_etaria text NOT NULL,
    ds_genero text,
    ds_estado_civil text,
    ds_grau_instrucao text,
    qt_eleitores_perfil text,
    source_file text NOT NULL
);

-- Cadastro com códigos oficiais TSE. CD_MUNICIPIO_IBGE só pode ser preenchido
-- com correspondência territorial comprovada; sem ela, manter NULL.
CREATE TABLE IF NOT EXISTS stg_tse.municipio_correspondencia (
    cd_municipio_tse text PRIMARY KEY,
    cd_municipio_ibge text,
    nm_municipio text,
    sg_uf text NOT NULL,
    source_file text NOT NULL
);

CREATE TABLE IF NOT EXISTS stg_tse.bem_candidato (
    ano_eleicao text NOT NULL,
    sq_candidato text NOT NULL,
    nr_ordem_bem_candidato text NOT NULL,
    ds_tipo_bem_candidato text,
    ds_bem_candidato text,
    vr_bem_candidato text,
    source_file text NOT NULL
);

-- Os arquivos anuais de contas variam. Primeiro normalize apenas estes campos
-- depois de confirmar o leia-me e o cabeçalho do arquivo de cada ano.
CREATE TABLE IF NOT EXISTS stg_tse.receita_candidato (
    ano_eleicao text NOT NULL,
    sq_candidato text NOT NULL,
    id_linha_origem text NOT NULL,
    ds_fonte_receita text,
    vr_receita text,
    tp_origem_recurso text,
    source_file text NOT NULL
);

CREATE TABLE IF NOT EXISTS stg_tse.despesa_candidato (
    ano_eleicao text NOT NULL,
    sq_candidato text NOT NULL,
    id_linha_origem text NOT NULL,
    ds_despesa text,
    ds_categoria_despesa text,
    vr_pago text,
    source_file text NOT NULL
);

-- Chave técnica da candidatura. Após 05/03, vários pares ano/SQ podem
-- compartilhar o ID da pessoa identificada pelo título eleitoral.
CREATE TABLE IF NOT EXISTS stg_tse.mapa_candidatura (
    ano_eleicao integer NOT NULL,
    sq_candidato bigint NOT NULL,
    id_pessoa_projeto integer GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (ano_eleicao, sq_candidato),
    UNIQUE (id_pessoa_projeto)
);

-- IDs estáveis para linhas financeiras, sem depender da posição atual no CSV.
CREATE TABLE IF NOT EXISTS stg_tse.mapa_lancamento (
    id_lancamento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_registro text NOT NULL CHECK (tipo_registro IN ('RECEITA', 'DESPESA')),
    ano_eleicao integer NOT NULL,
    sq_candidato bigint NOT NULL,
    id_linha_origem text NOT NULL,
    UNIQUE (tipo_registro, ano_eleicao, sq_candidato, id_linha_origem)
);

-- Converte valores monetários com vírgula decimal ou ponto decimal. Sentinelas
-- e formatos inesperados resultam em NULL, nunca em zero.
CREATE OR REPLACE FUNCTION stg_tse.parse_brl_amount(valor text)
RETURNS numeric(14,2)
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    v text := trim(valor);
BEGIN
    IF v IS NULL OR upper(v) IN ('', '#NULO', '#NE', '-1', '-3', '-4', 'NÃO DIVULGÁVEL') THEN
        RETURN NULL;
    END IF;
    IF position(',' IN v) > 0 THEN
        v := replace(replace(v, '.', ''), ',', '.');
    END IF;
    IF v !~ '^-?[0-9]+(\.[0-9]{1,2})?$' THEN
        RETURN NULL;
    END IF;
    RETURN v::numeric(14,2);
EXCEPTION WHEN numeric_value_out_of_range OR invalid_text_representation THEN
    RETURN NULL;
END;
$$;

-- Instrução de carga local (ajustar nomes/ordem após harmonizar cabeçalhos):
-- psql -d "$DATABASE_URL" -c "\\copy stg_tse.candidatura (...) FROM '...csv' WITH (FORMAT csv, HEADER true, DELIMITER ';', QUOTE '\"', ENCODING 'LATIN1')"
-- Atenção: \\copy aceita uma lista explícita de colunas. A ordem acima NÃO
-- corresponde diretamente aos CSVs TSE; não carregar CSV bruto sem mapeá-lo.

-- Complementar: campos oficiais mínimos; NR_TURNO só é preenchido se existir
-- no leiaute anual. CD_ELEICAO sempre participa da correspondência.
CREATE TABLE IF NOT EXISTS stg_tse.candidatura_complementar (
    ano_eleicao text NOT NULL,
    cd_eleicao text NOT NULL,
    sq_candidato text NOT NULL,
    nr_turno text,
    nm_tipo_destinacao_votos text,
    source_file text NOT NULL
);
CREATE TABLE IF NOT EXISTS stg_tse.destinacao_votos (
    ano_eleicao integer NOT NULL,
    cd_eleicao integer NOT NULL,
    sq_candidato bigint NOT NULL,
    nm_tipo_destinacao_votos text,
    source_files text[] NOT NULL,
    PRIMARY KEY (ano_eleicao, cd_eleicao, sq_candidato)
);

-- Lista de zonas esperadas: extrair do arquivo completo conferido, ANTES de
-- filtragens/normalizações. Não inferir cobertura somente das linhas aceitas.
-- manifesto_verificado só deve ser true após conferir integridade do arquivo.
CREATE TABLE IF NOT EXISTS stg_tse.comparecimento_zonas_esperadas (
    ano_eleicao integer NOT NULL,
    cd_eleicao integer NOT NULL,
    nr_turno integer NOT NULL CHECK (nr_turno IN (1, 2)),
    cd_municipio_tse text NOT NULL,
    nr_zona integer NOT NULL,
    source_manifest text NOT NULL,
    manifesto_verificado boolean NOT NULL DEFAULT false,
    PRIMARY KEY (ano_eleicao, cd_eleicao, nr_turno, cd_municipio_tse, nr_zona)
);
-- Lote financeiro corrente, separado do histórico persistente de cobertura.
-- Permite processar um ano por vez sem que a reconciliação de despesas de um
-- ano remova linhas já publicadas para os outros anos.
CREATE TABLE IF NOT EXISTS stg_tse.cobertura_despesa_paga_lote (
    ano_eleicao integer NOT NULL, sq_candidato bigint NOT NULL,
    completo boolean NOT NULL, source_manifest text NOT NULL,
    PRIMARY KEY (ano_eleicao, sq_candidato)
);
CREATE TABLE IF NOT EXISTS stg_tse.quarentena_comparecimento (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ano_eleicao bigint,
    cd_eleicao bigint,
    nr_turno bigint,
    cd_municipio_tse text,
    nr_zona bigint,
    motivo text NOT NULL,
    registros_origem jsonb NOT NULL,
    registrado_em timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION stg_tse.texto_publicado(valor text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE WHEN upper(trim(valor)) IN
        ('', '#NULO', '#NE', '-1', '-3', '-4', 'NÃO DIVULGÁVEL')
        THEN NULL ELSE trim(valor) END
$$;
CREATE OR REPLACE FUNCTION stg_tse.inteiro_nao_negativo(valor text)
RETURNS bigint LANGUAGE plpgsql IMMUTABLE AS $$
BEGIN
    IF trim(valor) !~ '^[0-9]+$' THEN RETURN NULL; END IF;
    RETURN trim(valor)::bigint;
EXCEPTION WHEN numeric_value_out_of_range OR invalid_text_representation THEN
    RETURN NULL;
END;
$$;

-- Maior turno com situação informada e não transitória. Se nenhuma situação
-- terminal existe, turno e resultado ficam NULL. Arquivo não decide o turno.
ALTER TABLE stg_tse.candidatura ADD COLUMN IF NOT EXISTS nr_titulo_eleitoral_candidato text;
DROP VIEW IF EXISTS stg_tse.candidatura_resultado;
CREATE OR REPLACE VIEW stg_tse.candidatura_resultado AS
WITH base AS (
    SELECT s.*,
           stg_tse.inteiro_nao_negativo(ano_eleicao) AS ano_id,
           stg_tse.inteiro_nao_negativo(sq_candidato) AS candidato_id,
           CASE WHEN stg_tse.inteiro_nao_negativo(nr_turno) IN (1, 2)
                AND stg_tse.texto_publicado(ds_sit_tot_turno) IS NOT NULL
                AND upper(trim(ds_sit_tot_turno)) NOT IN
                    ('2º TURNO', '2° TURNO', '2 TURNO', 'SEGUNDO TURNO')
                THEN stg_tse.inteiro_nao_negativo(nr_turno) END AS turno_resultado,
           stg_tse.texto_publicado(ds_sit_tot_turno) AS situacao_informada
    FROM stg_tse.candidatura s
    WHERE upper(trim(s.sg_uf)) IN (SELECT sg_uf::text FROM stg_tse.escopo_uf)
       OR upper(trim(s.sg_uf)) = 'BR'
), prioridade AS (
    SELECT b.*, dense_rank() OVER (
        PARTITION BY ano_id, candidato_id
        ORDER BY turno_resultado DESC NULLS LAST
    ) AS prioridade_resultado
    FROM base b WHERE ano_id IS NOT NULL AND candidato_id IS NOT NULL
)
SELECT * FROM prioridade WHERE prioridade_resultado = 1;

-- Mantém todas as votações de origem; ausência de complemento é INDEFINIDO.
-- Não associar o complemento ao ano/SQ ignorando CD_ELEICAO.
CREATE OR REPLACE VIEW stg_tse.votacao_candidato_com_destinacao AS
SELECT v.*, d.nm_tipo_destinacao_votos,
       CASE WHEN upper(d.nm_tipo_destinacao_votos) IN ('VÁLIDO', 'VALIDO')
                 THEN 'VALIDO'
            WHEN d.nm_tipo_destinacao_votos IS NULL THEN 'INDEFINIDO'
            ELSE 'OUTRA_DESTINACAO' END AS universo_destinacao
FROM stg_tse.votacao_candidato_munzona v
LEFT JOIN stg_tse.destinacao_votos d
  ON d.ano_eleicao = stg_tse.inteiro_nao_negativo(v.ano_eleicao)
 AND d.cd_eleicao = stg_tse.inteiro_nao_negativo(v.cd_eleicao)
 AND d.sq_candidato = stg_tse.inteiro_nao_negativo(v.sq_candidato);
CREATE OR REPLACE VIEW stg_tse.votacao_candidato_valida AS
SELECT * FROM stg_tse.votacao_candidato_com_destinacao
WHERE universo_destinacao = 'VALIDO';

-- Preserva linhas inválidas no grupo: não removê-las antes de avaliar cobertura.
CREATE OR REPLACE VIEW stg_tse.comparecimento_zonas AS
WITH base AS (
    SELECT stg_tse.inteiro_nao_negativo(s.ano_eleicao) AS ano_eleicao,
           stg_tse.inteiro_nao_negativo(s.cd_eleicao) AS cd_eleicao,
           stg_tse.inteiro_nao_negativo(s.nr_turno) AS nr_turno,
           trim(s.cd_municipio_tse) AS cd_municipio_tse,
           stg_tse.inteiro_nao_negativo(s.nr_zona) AS nr_zona,
           stg_tse.inteiro_nao_negativo(s.qt_aptos) AS aptos,
           stg_tse.inteiro_nao_negativo(s.qt_comparecimento) AS presentes,
           stg_tse.inteiro_nao_negativo(s.qt_abstencao) AS ausentes,
           to_jsonb(s) AS origem
    FROM stg_tse.detalhe_votacao_munzona s
    JOIN stg_tse.escopo_uf uf ON uf.sg_uf = upper(trim(s.sg_uf))
)
SELECT ano_eleicao, cd_eleicao, nr_turno, cd_municipio_tse, nr_zona,
       max(aptos) AS qt_aptos, max(presentes) AS qt_comparecimento,
       max(ausentes) AS qt_abstencao,
       count(DISTINCT (aptos, presentes, ausentes)) AS combinacoes,
       bool_and(aptos IS NOT NULL AND presentes IS NOT NULL
                AND ausentes IS NOT NULL AND aptos::numeric = presentes::numeric + ausentes::numeric
                AND aptos <= 2147483647 AND presentes <= 2147483647
                AND ausentes <= 2147483647) AS medidas_validas,
       jsonb_agg(origem) AS registros_origem
FROM base
GROUP BY ano_eleicao, cd_eleicao, nr_turno, cd_municipio_tse, nr_zona;

CREATE OR REPLACE VIEW stg_tse.comparecimento_cobertura AS
WITH esperadas AS (
    SELECT e.* FROM stg_tse.comparecimento_zonas_esperadas e
    JOIN stg_tse.municipio_correspondencia m USING (cd_municipio_tse)
    JOIN stg_tse.escopo_uf uf ON uf.sg_uf = upper(trim(m.sg_uf))
), confronto AS (
    SELECT coalesce(e.ano_eleicao, z.ano_eleicao) AS ano_eleicao,
           coalesce(e.cd_eleicao, z.cd_eleicao) AS cd_eleicao,
           coalesce(e.nr_turno, z.nr_turno) AS nr_turno,
           coalesce(e.cd_municipio_tse, z.cd_municipio_tse) AS cd_municipio_tse,
           e.nr_zona AS zona_esperada, z.nr_zona AS zona_observada,
           e.manifesto_verificado,
           z.medidas_validas, z.combinacoes,
           z.qt_aptos, z.qt_comparecimento, z.qt_abstencao
    FROM esperadas e FULL JOIN stg_tse.comparecimento_zonas z
      ON e.ano_eleicao = z.ano_eleicao AND e.cd_eleicao = z.cd_eleicao
     AND e.nr_turno = z.nr_turno AND e.cd_municipio_tse = z.cd_municipio_tse
     AND e.nr_zona = z.nr_zona
)
SELECT ano_eleicao, cd_eleicao, nr_turno, cd_municipio_tse,
       count(zona_esperada) AS zonas_esperadas,
       count(zona_observada) AS zonas_observadas,
       bool_and(coalesce(zona_esperada IS NOT NULL AND zona_observada IS NOT NULL
                AND manifesto_verificado AND medidas_validas AND combinacoes = 1, false))
           AND count(zona_esperada) > 0 AS completo,
       sum(qt_aptos::numeric) AS qt_aptos,
       sum(qt_comparecimento::numeric) AS qt_comparecimento,
       sum(qt_abstencao::numeric) AS qt_abstencao
FROM confronto
GROUP BY ano_eleicao, cd_eleicao, nr_turno, cd_municipio_tse;
